"""System Events tools – retrieve FortiEDR platform health events."""

import logging
from typing import Any, Optional

from fastmcp import FastMCP

from ..api.client import client

logger = logging.getLogger(__name__)


def register(mcp: FastMCP) -> None:
    """Register all system events tools on the given FastMCP instance."""

    @mcp.tool()
    async def system_events_list(
        organization: Optional[str] = None,
        component_names: Optional[str] = None,
        component_types: Optional[str] = None,
        from_date: Optional[str] = None,
        to_date: Optional[str] = None,
        strict_mode: Optional[bool] = None,
        items_per_page: Optional[int] = None,
        page_number: Optional[int] = None,
        sorting: Optional[str] = None,
    ) -> Any:
        """List FortiEDR platform system events (health and operational alerts).

        Returns events generated by the FortiEDR platform itself (not endpoint
        security events), such as component connectivity issues, license warnings,
        and update notifications.

        Args:
            organization: Organization name or None for all.
            component_names: Comma-separated component names to filter
                (e.g., 'Core', 'Aggregator', 'Collector').
            component_types: Comma-separated component types to filter.
            from_date: ISO-8601 start datetime for the event time range.
            to_date: ISO-8601 end datetime for the event time range.
            strict_mode: If True, use exact matching for string filters.
            items_per_page: Results per page.
            page_number: Page number (1-based).
            sorting: Sort expression, e.g. 'date desc'.
        """
        return await client.get(
            "/management-rest/system-events/list-system-events",
            params={
                "organization": organization,
                "componentNames": component_names,
                "componentTypes": component_types,
                "fromDate": from_date,
                "toDate": to_date,
                "strictMode": strict_mode,
                "itemsPerPage": items_per_page,
                "pageNumber": page_number,
                "sorting": sorting,
            },
        )
